<#
.SYNOPSIS
    Pre-build script for the PluginsInstaller WiX project.
    1. Calls prepare-release.ps1 to populate staging\.
    2. Generates Files.wxs by walking staging\ so WiX can compile it.

.PARAMETER Configuration
    MSBuild configuration (Debug | Release).
.PARAMETER OutputWxs
    Path for the generated Files.wxs.  Defaults to .\Files.wxs.
#>
param(
    [string]$Configuration = "Release",
    [string]$OutputWxs     = ""
)

$ErrorActionPreference = "Stop"

$installerDir  = Split-Path $MyInvocation.MyCommand.Path -Parent
$pluginUiDir   = Split-Path $installerDir -Parent
$repoRoot        = Split-Path $pluginUiDir -Parent
$prepareScript = Join-Path $pluginUiDir "prepare-release.ps1"
$extensionDir  = Join-Path $repoRoot "Extension"
$stagingDir    = Join-Path $pluginUiDir "staging"

# Pick the latest .vsix from Extension\ (sorted by LastWriteTime)
$latestVsix = Get-ChildItem $extensionDir -Filter "*.vsix" -ErrorAction SilentlyContinue |
                Sort-Object LastWriteTime -Descending |
                Select-Object -First 1
$vsixPath = if ($latestVsix) { $latestVsix.FullName } else { "" }

if ([string]::IsNullOrWhiteSpace($OutputWxs)) {
    $OutputWxs = Join-Path $installerDir "Files.wxs"
}

# ---- Step 1: Populate staging\ -----------------------------------------------
Write-Host ""
Write-Host "=== PluginsInstaller PreBuild ===" -ForegroundColor Cyan

$stagingOk = (Test-Path $stagingDir) -and
             (Test-Path (Join-Path $stagingDir "PluginsUI.exe"))

if ($stagingOk -and
    ($env:PLUGINSUI_REBUILD_STAGING -ne "1") -and
    ($env:PLUGINSUI_FULL_BUILD      -ne "1"))
{
    Write-Host "  staging\ already populated -- skipping prepare-release.ps1" -ForegroundColor DarkGray
    Write-Host "  (Set PLUGINSUI_REBUILD_STAGING=1 to force a rebuild)" -ForegroundColor DarkGray
}
else
{
    if ($env:PLUGINSUI_FULL_BUILD -eq "1") {
        Write-Host "  Mode: FULL BUILD (PLUGINSUI_FULL_BUILD=1)"
        & $prepareScript -Configuration $Configuration
    }
    elseif ($vsixPath -and (Test-Path $vsixPath)) {
        Write-Host "  Mode: -FromVsix  ($vsixPath)" -ForegroundColor Green
        & $prepareScript -Configuration $Configuration -FromVsix -VsixPath $vsixPath
    }
    else {
        Write-Host "  Mode: -SkipAngularBuild" -ForegroundColor Yellow
        & $prepareScript -Configuration $Configuration -SkipAngularBuild
    }

    if ($LASTEXITCODE -ne 0) {
        Write-Error "prepare-release.ps1 failed (exit $LASTEXITCODE)"
        exit $LASTEXITCODE
    }
}

# ---- Step 2: Generate Files.wxs from staging\ --------------------------------
Write-Host "  Generating Files.wxs from staging\ ..." -ForegroundColor Cyan

$stagingResolved = (Resolve-Path $stagingDir).Path.TrimEnd('\')
$files           = Get-ChildItem $stagingResolved -Recurse -File
$sha256          = [System.Security.Cryptography.SHA256]::Create()

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
[void]$sb.AppendLine('<!-- AUTO-GENERATED by PreBuild.ps1. Do not edit manually. -->')
[void]$sb.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
[void]$sb.AppendLine('  <Fragment>')
[void]$sb.AppendLine('    <ComponentGroup Id="StagingComponents" Directory="INSTALLDIR">')

$count = 0
foreach ($file in $files) {
    # Relative path from staging root, e.g.  "dist\index.js"
    $relPath = $file.FullName.Substring($stagingResolved.Length + 1)
    $source  = "..\staging\$relPath"
    $subdir  = Split-Path $relPath -Parent

    # Deterministic unique ID: SHA-256 of the lowercase relative path (first 16 bytes)
    $hashBytes = $sha256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($relPath.ToLower()))
    $id = 'cmp_' + ([BitConverter]::ToString($hashBytes[0..15]).Replace('-',''))

    if ($subdir) {
        [void]$sb.AppendLine("      <Component Id=""$id"" Guid=""*"" Subdirectory=""$subdir"">")
    } else {
        [void]$sb.AppendLine("      <Component Id=""$id"" Guid=""*"">")
    }
    [void]$sb.AppendLine("        <File Source=""$source"" />")
    [void]$sb.AppendLine("      </Component>")
    $count++
}

[void]$sb.AppendLine('    </ComponentGroup>')
[void]$sb.AppendLine('  </Fragment>')
[void]$sb.AppendLine('</Wix>')

$sb.ToString() | Set-Content -Path $OutputWxs -Encoding UTF8

Write-Host "  Files.wxs written -- $count components." -ForegroundColor Green
Write-Host ""
